fix: try a different approach

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -69,11 +69,19 @@ jobs:
       - uses: cachix/install-nix-action@v17
         with:
           nix_path: nixpkgs=channel:nixos-unstable
-      - name: Run code generation
-        run: make generate
+      - name: Run 'make proto'
+        run: make proto
       - name: Error if there are any changes
         run: |
           if ! git diff --name-only --exit-code; then
-              echo '::error ::"Please run `make generate` locally and commit the changes"'
+              echo '::error ::"Please run `make proto` locally and commit the changes"'
+              exit 1
+          fi
+      - name: Run 'make testdata'
+        run: make testdata
+      - name: Error if there are any changes
+        run: |
+          if ! git diff --name-only --exit-code; then
+              echo '::error ::"Please run `make testdata` locally and commit the changes"'
               exit 1
           fi
