fix: check code generation on ci

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -55,3 +55,25 @@ jobs:
         run: go mod download
       - name: Run tests
         run: go test ./... -v
+
+  makeGenerateNoOp:
+    runs-on: ubuntu-latest
+    name: Check we didn't forget to run code generation
+    steps:
+      - uses: actions/checkout@v3
+      - name: git-config
+        env:
+          GITHUB_API_TOKEN: ${{secrets.CI_GITHUB_API_TOKEN}}
+        run: git config --global url."https://${{ secrets.CI_GITHUB_API_TOKEN }}:x-oauth-basic@github.com/teamkeel".insteadOf "https://github.com/teamkeel"
+      - uses: actions/checkout@v2
+      - uses: cachix/install-nix-action@v17
+        with:
+          nix_path: nixpkgs=channel:nixos-unstable
+      - name: Run code generation
+        run: make generate
+      - name: Error if there are any changes
+        run: |
+          if ! git diff --name-only --exit-code; then
+              echo '::error ::"Please run `make generate` locally and commit the changes"'
+              exit 1
+          fi
